{% set name = "libcusparse" %}
{% set version = "12.6.3.3" %}
{% set cuda_version = "13.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: b9de356c3478329e2589d91284f2a685a36f041060f3cb897441ab46a480a30a  # [linux64]
  sha256: 50c9fb74e8468af559150f3f072cc2793a5ff70792fa79962146096385cf7346  # [aarch64]
  sha256: 21f70385aae76de5c24c6baab4df4337d0bc9e1ce69e9ebad228d87d686a28e6  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0     # [linux]

outputs:
  - name: libcusparse
    files:
      - lib/libcusparse.so.*                             # [linux]
      - targets/{{ target_name }}/lib/libcusparse*.so.*  # [linux]
      - Library\bin\cusparse*.dll      # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink =={{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink", max_pin="x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcusparse.so.{{ version }}                                  # [linux]
        - test -L $PREFIX/lib/libcusparse.so.{{ version.split(".")[0] }}                    # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusparse.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusparse.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                        # [linux]
        - if not exist %LIBRARY_BIN%\cusparse*.dll exit 1                         # [win]
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

  - name: libcusparse-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcusparse", max_pin="x") }}
    files:
      - lib/libcusparse.so         # [linux]
      - lib/pkgconfig                                 # [linux]
      - targets/{{ target_name }}/include             # [linux]
      - targets/{{ target_name }}/lib/libcusparse.so  # [linux]
      - targets/{{ target_name }}/lib/stubs           # [linux]
      # Not shipping Fortran bindings (in src) on Windows for now
      - targets/{{ target_name }}/libcusparse/src     # [linux]
      - Library\include                             # [win]
      - Library\lib\{{ target_name }}                 # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink =={{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink", max_pin="x") }}
        - {{ pin_subpackage("libcusparse", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libcusparse-static >={{ version }}  # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libcusparse.so                                                   # [linux]
        - test -f $PREFIX/lib/pkgconfig/cusparse*.pc                                           # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusparse.h                         # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusparse.so                         # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcusparse.so                   # [linux]
        # These `src` files are only available on Linux x86_64 (not aarch64 or ppc64le)
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran.c         # [linux64]
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran.h         # [linux64]
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran_common.h  # [linux64]
        - if not exist %LIBRARY_INC%\cusparse.h exit 1                                         # [win]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cusparse.lib exit 1                     # [win]
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

  - name: libcusparse-static
    build:
      skip: true  # [win]
    files:
      - targets/{{ target_name }}/lib/libcusparse_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink-static =={{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink-static", max_pin="x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusparse_static.a
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

about:
  home: https://developer.nvidia.com/cusparse
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Sparse Matrix Library
  description: |
    cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
  doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

extra:
  feedstock-name: libcusparse
  recipe-maintainers:
    - conda-forge/cuda
